apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    internal.kpt.dev/upstream-identifier: apps|Deployment|default|image-classifier
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"internal.kpt.dev/upstream-identifier":"apps|Deployment|default|image-classifier"},"labels":{"app":"image-classifier"},"name":"image-classifier","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"image-classifier"}},"template":{"metadata":{"labels":{"app":"image-classifier"}},"spec":{"containers":[{"args":["--model_name=$(MODEL_NAME)","--model_base_path=$(MODEL_PATH)"],"envFrom":[{"configMapRef":{"name":"tfserving-configs"}}],"image":"tensorflow/serving:2.8.0","imagePullPolicy":"IfNotPresent","name":"tf-serving","ports":[{"containerPort":8501,"name":"http","protocol":"TCP"},{"containerPort":8500,"name":"grpc","protocol":"TCP"}],"readinessProbe":{"failureThreshold":10,"initialDelaySeconds":10,"periodSeconds":5,"tcpSocket":{"port":8500}},"resources":{"requests":{"cpu":"3","memory":"4Gi"}}}]}}}}
  creationTimestamp: "2026-01-26T08:22:37Z"
  generation: 1
  labels:
    app: image-classifier
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:internal.kpt.dev/upstream-identifier: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"tf-serving"}:
                .: {}
                f:args: {}
                f:envFrom: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8500,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":8501,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:readinessProbe:
                  .: {}
                  f:failureThreshold: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:tcpSocket:
                    .: {}
                    f:port: {}
                  f:timeoutSeconds: {}
                f:resources:
                  .: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2026-01-26T08:22:37Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2026-01-26T08:22:58Z"
  name: image-classifier
  namespace: default
  resourceVersion: "1769415778615935001"
  uid: 980d767d-cc77-4277-906a-b88cf8cee413
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: image-classifier
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: image-classifier
    spec:
      containers:
      - args:
        - --model_name=$(MODEL_NAME)
        - --model_base_path=$(MODEL_PATH)
        envFrom:
        - configMapRef:
            name: tfserving-configs
        image: tensorflow/serving:2.8.0
        imagePullPolicy: IfNotPresent
        name: tf-serving
        ports:
        - containerPort: 8501
          name: http
          protocol: TCP
        - containerPort: 8500
          name: grpc
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8500
          timeoutSeconds: 1
        resources:
          requests:
            cpu: "3"
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-01-26T08:22:58Z"
    lastUpdateTime: "2026-01-26T08:22:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-01-26T08:22:37Z"
    lastUpdateTime: "2026-01-26T08:22:58Z"
    message: ReplicaSet "image-classifier-567658456b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
